version: '3'

services:
  mongo:
    image: mongo:4.2
    restart: on-failure
    volumes:
      - 'mongodb-data:/data/db'
  api:
    build: ./api
    image: mqm-api:latest
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      - mongo
  ui:
    build: ./ui
    image: mqm-ui:latest
    restart: on-failure
    ports:
      - "8081:80"

volumes:
  mongodb-data:
